/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.henriquemcc.computacaografica.trabalhopratico

import io.github.henriquemcc.computacaografica.trabalhopratico.controlador.ControladorGrafico
import io.github.henriquemcc.computacaografica.trabalhopratico.visao.janela.Janela
import io.github.henriquemcc.computacaografica.trabalhopratico.visao.obterResolucaoTela
import javax.swing.JFrame

val janela = Janela()
val controladorGrafico = ControladorGrafico(janela)

fun main()
{
	janela.defaultCloseOperation = JFrame.EXIT_ON_CLOSE
	janela.size = obterResolucaoTela()
	janela.extendedState = JFrame.MAXIMIZED_BOTH
	janela.isVisible = true
}
