/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.henriquemcc.computacaografica.trabalhopratico

import io.github.henriquemcc.computacaografica.trabalhopratico.controlador.ControladorGrafico
import io.github.henriquemcc.computacaografica.trabalhopratico.visao.JanelaPrincipal
import io.github.henriquemcc.computacaografica.trabalhopratico.visao.obterResolucaoTela
import javax.swing.JFrame

fun main()
{
	val controladorGrafico = ControladorGrafico()
}
